pub mod account_page;
pub mod dashboard_page;
pub mod home_page;
pub mod login_page;
pub mod maps_page;
pub mod not_found;
pub mod parser_page;
pub mod register_page;
pub mod users_page;

pub use self::account_page::AccountPage;
pub use self::dashboard_page::DashboardPage;
pub use self::home_page::HomePage;
pub use self::login_page::LoginPage;
pub use self::maps_page::MapsPage;
pub use self::not_found::NotFoundPage;
pub use self::parser_page::ParserPage;
pub use self::register_page::RegisterPage;
pub use self::users_page::UsersPage;
